CREATE TABLE IF NOT EXISTS extensions (
    ID CHAR(36) PRIMARY KEY,
    COMPANY_ID CHAR(36) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    ENABLED TINYINT(1) DEFAULT 1,
    ENDPOINT_URL VARCHAR(1000) NOT NULL,
    HTTP_METHOD ENUM('GET', 'POST') DEFAULT 'GET',
    AUTH_TYPE ENUM('none', 'bearer', 'api-key', 'basic') DEFAULT 'none',
    AUTH_CONFIG TEXT,
    REQUEST_HEADERS JSON,
    REQUEST_BODY_TEMPLATE TEXT,
    RESPONSE_PATH VARCHAR(255) DEFAULT '$',
    SCHEMA_MAPPING JSON,
    DISPLAY_TYPE ENUM('page', 'project-tab', 'dashboard-widget') DEFAULT 'page',
    DISPLAY_CONFIG JSON NOT NULL,
    REFRESH_INTERVAL INT DEFAULT NULL,
    LAST_SYNC DATETIME DEFAULT NULL,
    CREATED_BY CHAR(36) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_company (COMPANY_ID),
    INDEX idx_enabled (ENABLED)
);

CREATE TABLE IF NOT EXISTS extension_data (
    ID CHAR(36) PRIMARY KEY,
    EXTENSION_ID CHAR(36) NOT NULL,
    PROJECT_ID CHAR(36) DEFAULT NULL,
    RAW_DATA JSON NOT NULL,
    TRANSFORMED_DATA JSON,
    FETCHED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_extension (EXTENSION_ID),
    INDEX idx_project (PROJECT_ID)
);
